# Generated by Django 4.0.3 on 2022-04-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_catgory',
            new_name='variation_category',
        ),
    ]
